#!/usr/bin/zsh

brightness_f='/sys/class/backlight/nv_backlight/brightness'
brightness=$(< "${brightness_f}")

if [[ ${1:u} == 'UP' ]]; then
	print $(( brightness + 20 )) > "${brightness_f}"
elif [[ ${1:u} == 'DOWN' ]]; then
	print $(( brightness - 20 )) > "${brightness_f}"
else
	print "Usage: ${0:t} {UP|DOWN}" >&2
	exit 1
fi
