#!/usr/bin/zsh
intern='LVDS-1'
extern='VGA-1'
mode='1280x720'

nosleep

xrandr | awk "
	/${intern}/ { output = 0 }
	/${extern}/ { output = 1 }
	/${mode}/ {
		if (output)
			exit 1
	}
"

if (( ? == 0 )); then
	modeline=$(cvt ${(s:x:)mode} | awk '/Modeline/ {$1=$2=""; print $0}')
	xrandr --newmode "${mode}" ${=modeline}
	xrandr --addmode "${extern}" "${mode}"
fi

if xrandr | grep -B1 '\*' | grep -q "${intern}" &&
   xrandr | grep -q "${extern} connected"; then
	xrandr --output "${intern}" --off --output "${extern}" --mode "${mode}"
else
	xrandr --output "${extern}" --off --output "${intern}" --auto
fi

rect=$(xrandr | awk '/\*/ {print $1}')
bspc monitor --rectangle "${rect}+0+0"
setbg

# xrandr --output "${intern}" --auto --right-of "${extern}"
