#!/usr/bin/zsh
intern='LVDS-1'
extern='VGA-1'
mode='1360x720'

modeline=$(cvt ${(s:x:)mode} | awk '/Modeline/ {$1=$2=""; print $0}')
xrandr --newmode "${mode}" ${=modeline}
xrandr --addmode "${extern}" "${mode}"

if xrandr | grep -B1 '\*' | grep "${intern}" &&
   xrandr | grep "${extern} connected"; then
	xrandr --output "${intern}" --off --output "${extern}" --mode "${mode}"
else
	xrandr --output "${extern}" --off --output "${intern}" --auto
fi

rect=$(xrandr | awk '/\*/ {print $1}')
bspc monitor --rectangle "${rect}+0+0"
setbg
