#!/bin/bash

f=3 b=4 
for j in f b; do
  for i in {0..7}; do
    printf -v $j$i %b "\e[${!j}${i}m"
  done
done
bld=$'\e[1m'
rst=$'\e[0m'

cat << EOF

      $f3▄▄█████▄▄$rst                                                              $f5▄▄████▄▄$rst
     $f3███████████$rst                          ▄████▄                           $f5▄██████████▄$rst
    $f3███████▀▀▀$rst      ▄▄      ▄▄      ▄▄   ████████   ▄▄      ▄▄      ▄▄     $f5$b7██▀  ▀██▀  ▀$rst
    $f3████▄▄▄$rst         ▀▀      ▀▀      ▀▀   ████████   ▀▀      ▀▀      ▀▀    $f5$b7███  $f4██$f5██  $f4██$f5█$rst
    $f3▀█████████▄▄$rst                          ▀████▀                          $f5$b7████▄▄████▄▄██$rst
     $f3▀█████████▀$rst                                                          $f5██████████████$rst
        $f3▀▀▀▀▀$rst                                                             $f5█▀ ▀██  ██▀ ▀█$rst

EOF
