#!/usr/bin/zsh
disk=$(dirname "${0}")/disk.qcow2

if [[ ! -f "${disk}" ]]; then
	qemu-img create -f qcow2 "${disk}" 8G
fi

if [[ ${1} ]]; then
	discopts=( -cdrom "${1}" -boot order=d )
fi

qemu-system-x86_64 -enable-kvm -cpu host -smp 2 -m 2G -net nic,model=pcnet -net user -vga vmware -usbdevice mouse ${discopts} "${disk}"
