#!/usr/bin/python
import json
from subprocess import Popen, PIPE

query = ('bspc', 'query', '-T', '-n', 'focused')

with Popen(query, stdout=PIPE, universal_newlines=True) as p:
    attrs = json.load(p.stdout)

if not attrs['presel']:
    rect = attrs['client']['tiledRectangle']
    split_dir = 'east' if rect['width'] >= rect['height'] else 'south'
    print('split_dir=', split_dir, sep='')
