#!/usr/bin/env python
import json
import os
import re
import subprocess
import sys
import time

if len(sys.argv) != 2:
    sys.exit(f'Usage: mhg DIR')

os.chdir(sys.argv[1])
print('Fetching ', sys.argv[1], ' ...')

with open('curl') as f:
    curl_template = f.read().rstrip('\n')

with open('pages') as f:
    pages = json.load(f)

for i, page in enumerate(pages):
    curl = re.sub('(?<=/)[^/]+(?=\?)', page, curl_template, count=1)
    outfile = '{:03}-{}'.format(i, re.sub('.png$', '.jpg', page, flags=re.IGNORECASE))
    curl += f'-sS --output {outfile}'

    if os.path.exists(outfile):
        print(f'{outfile} exists, skipping...')
        continue

    for _ in range(5):
        subprocess.run(curl, shell=True, check=True)
        if os.path.getsize(outfile) > 1000:
            break;
        time.sleep(3)
    else:
        os.remove(outfile)
        sys.exit(f'Failed to fetch {sys.argv[1]}/{outfile}, giving up')
