#!/usr/bin/env python
import json
import os
import re
import subprocess
import sys

if len(sys.argv) != 2:
    sys.exit(f'Usage: {sys.argv[0]} DIR')

os.chdir(sys.argv[1])

with open('curl') as f:
    curl_template = f.read().rstrip('\n')

with open('pages') as f:
    pages = json.load(f)

for i, page in enumerate(pages):
    print(f'Fetching {page}')
    curl = re.sub('(?<=/)[^/]+(?=\?)', page, curl_template, count=1) + f' --output {i:03}-{page}.jpg'
    subprocess.run(curl, shell=True, check=True)
