#!/usr/bin/zsh

zmodload zsh/net/socket
zsocket /tmp/mpv-socket || exit 1

print -u "${REPLY}" '{"command": ["'${(j:",":)@}'"]}'
while read -ert 1 -u "${REPLY}"; do
	# Read all incoming messages
done

exec {REPLY}>&-
