#!/bin/bash

CHANNEL="${HOME}/Videos/TV/Channels/$(basename ${1-NULL} .xspf).xspf"
DURATION=${2-60}
PID=-1

if [ ! -f ${CHANNEL} ]; then
	echo 'Channel not found'
	exit 1
fi

OUTFILE="${HOME}/Videos/TV/Recorded/$(basename ${CHANNEL} .xspf)-$(date -I).mp4"
cvlc "${CHANNEL}" --sout "#transcode{vcodec=h264,acodec=mp3,channels=2,samplerate=44100}:std{access=file,mux=mp4,dst=\"${OUTFILE}\""
PID=${!}

at NOW + ${DURATION} MINUTE << HERE
	if [ ${PID} != -1 ]; then
		kill ${PID}
	else
		pkill vlc
	fi
HERE
