#!/usr/bin/zsh

channel=${1}
typeset -i duration=${2}

if (( duration <= 0 )); then
	echo "Invalid duration '${2}'" >&2
	echo "Usage: ${0:t} CHANNEL MINUTES [OPTIONS]" >&2
	exit 1
fi

shift 2
outfile="${HOME}/Videos/TV/Recorded/${channel}_$(date -I).mpg"
mpv "dvb://${channel}" "${@}" --stream-dump="${outfile}" &!
pid=${!}

# TODO: use systemd-run
at now + "${duration}" minutes <<< "kill ${pid}"
