#!/usr/bin/env zsh

ext="${1:e}"
if [[ "${ext}" = (7z|zip) ]]; then
	ext=$(7z l -ba "${1}" 2>/dev/null | head -n1 | sed 's/.*\.//')
fi

case "${ext}" in
	a26) core='stella' ;;
	gb)  core='gambatte' ;;
	gbc) core='gambatte' ;;
	gba) core='mgba' ;;
	nes) core='mesen' ;;
	fds) core='mesen' ;;
	sfc) core='snes9x' ;;
	vb)  core='mednafen_vb' ;;
	z64) core='parallel_n64' ;;
esac

xset s off
xset -dpms

if [[ -v core ]]; then
	retroarch -L "${HOME}/.config/retroarch/cores/${core}_libretro.so" "${1}"
else
	retroarch "${@}"
fi

xset s on
xset +dpms

# The current save state slot always changes and clutters our git diff,
# so always reset it to the same value when retroarch exits.
sed -i 's/^\(state_slot =\).*/\1 "9"/' ~/.config/retroarch/retroarch.cfg

rotsave
stretchthumb
