#!/usr/bin/env sh
nosleep
retroarch "${@}"
rotsave

# The current save state slot always changes and clutters our git diff,
# so always reset it to the same value when retroarch exits.
sed -i 's/^\(state_slot =\).*/\1 "9"/' ~/.config/retroarch/retroarch.cfg
