#!/usr/bin/env zsh

zmodload zsh/mapfile
retro_dir="${HOME}/.config/retroarch"

rm -r "${retro_dir}/thumbnails/"*

for playlist in "${retro_dir}/playlists/"*; do
	snap_dir="${retro_dir}/thumbnails/${playlist:t:r}/Named_Snaps"
	mkdir -p "${snap_dir}"
	lines=("${(f@)mapfile[${playlist}]}")

	for ((i = 1; i < ${#lines}; i+=6 )); do
		game_file="${lines[i]:t:r}"
		game_title="${lines[i+1]}"

		state="${retro_dir}/states/${game_file}.state"
		thumb="${snap_dir}/${game_title}"

		for state in "${state}"{99..1} "${state}" "${state}.auto" ; do
			if [[ -f "${state}" ]]; then
				ln -sf "${state}.png" "${thumb}.png"
				break
			fi
		done
	done
done
