#!/usr/bin/env zsh

state_dir="${HOME}/.config/retroarch/states"

for thumb in "${state_dir}"/*.png; do
	size=$(identify -format '%wx%h' "${thumb}")

	if [[ "${size}" = '160x210' ]]; then
		mogrify -resize '260x210!' "${thumb}"
	fi
done
