#!/usr/bin/zsh

while [[ -n "${1}" ]]; do
	file=${1}
	dir=${file:h}
	base=${file:t:r}
	ext=${file:e}

	if [[ "${ext}" == 'mkv' ]]; then
		print "${0:t}: Skipping ${base}.${ext}"
		exit 1
	fi

	ffmpeg -i "${file}" -c copy "${dir}/${base}.mkv" && rm "${file}"

	shift
done
