#!/bin/zsh

channel=${1}

if [[ -z "${channel}" ]]; then
	echo "Usage: ${0:t} CHANNEL [OPTIONS]" >&2
	exit 1
fi

shift
outfile="/tmp/tv.mpg"
rm -f "${outfile}"
mpv "dvb://${channel}" "${@}" --stream-dump="${outfile}" &!
pid=${!}

for i in {1..20}; do
	sleep 1
	if [[ -f "${outfile}" ]]; then
		break
	fi
done

if [[ -f "${outfile}" ]]; then
	sleep 5
	mpv --keep-open "${outfile}" --title "${channel:u}"
else
	echo 'Could not tune to channel (timed out)' >&2
fi

kill ${pid}
