#!/bin/bash

channel=${1}
shift
outfile="/tmp/tv.mpg"

rm -f "${outfile}"
mpv "dvb://${channel}" "${@}" --vo=opengl --stream-dump="${outfile}" &!
pid=${!}

for i in {1..30}; do
	sleep 1
	if [[ -f "${outfile}" ]]; then
		break
	fi
done

if [[ -f "${outfile}" ]]; then
	sleep 5
	mpv --keep-open --vo=opengl "${outfile}" --title "${channel^^}"
else
	echo 'Could not tune to channel (timed out)' >&2
fi

kill ${pid}
