#!/usr/bin/sh
selection=$(xclip -o -selection clipboard)
bspc rule -a mpv -o state=fullscreen desktop=^1
mpv --force-window=immediate "${selection}" || notify-send -i 'totem' '<b>Failed to stream video</b>' "${selection}"
